import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { PRIVATE_ENV_VARS, PUBLIC_ENV_VARS } from "@/libs/environment";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { APP_VERSION } = PRIVATE_ENV_VARS;
  const { NEXT_PUBLIC_APP_NAME } = PUBLIC_ENV_VARS;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <footer>
          <p className="text-center">
            {NEXT_PUBLIC_APP_NAME} - v{APP_VERSION}
          </p>
        </footer>
      </body>
    </html>
  );
}
