import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { APP_VERSION, NEXT_PUBLIC_APP_NAME } from "@/env";

import { NextIntlClientProvider, hasLocale } from "next-intl";
import { notFound } from "next/navigation";
import { routing } from "@/i18n/routing";

import "./globals.css";
import FAQGeneralBlock from "@/components/faq/FAQGeneral.Block";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

type Props = {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
};

export default async function RootLayout({
  children,
  params,
}: Readonly<Props>) {
  // Ensure that the incoming `locale` is valid
  const { locale } = await params;
  const baseUrl = await import("@/libs/base-url").then((mod) =>
    mod.getBaseUrl()
  );
  if (!hasLocale(routing.locales, locale)) {
    notFound();
  }
  return (
    <html lang={locale}>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextIntlClientProvider>{children}</NextIntlClientProvider>
        <FAQGeneralBlock baseUrl={baseUrl} locale={locale} />
        <footer>
          <p className="text-center">
            {NEXT_PUBLIC_APP_NAME} - v{APP_VERSION} - {locale}
          </p>
        </footer>
      </body>
    </html>
  );
}
